version: "1.0"


volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local

services:
  keycloak:
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_USER_PASSWORD}
      PROXY_ADDRESS_FORWARDING: true
    image: jboss/keycloak:latest
    ports:
      - ${KEYCLOAK_HOST_PORT}:${KEYCLOAK_CONTAINER_PORT}
    restart: unless-stopped
    volumes: 
      - keycloak_data:${KEYCLOAK_VOLUMES}
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - postgres_data:${POSTGRES_VOLUMES}